#!/bin/sh
prog=$(basename $0)
bindir=$(dirname $(readlink -f $0))
libdir=$(dirname $bindir)/lib

if [ "$1" = "--list-command" ]; then
	echo "list list-app id help"
	exit 0
fi

. $libdir/common.subr

USAGE="usage:
    $OCEAN_COMMAND $prog list
    $OCEAN_COMMAND $prog list-app
    $OCEAN_COMMAND $prog id <name>
    $OCEAN_COMMAND $prog help
" # END-QUOTE

cmd=$1
shift
case "$cmd" in
	list|list-dist*)
		doctl compute image list-distribution --public "$@"
		;;
	list-app*)
		doctl compute image list-application --public "$@"
		;;
	id)
		usage_exit_unless "$1"
		id=$(doctl compute image get "$1" --no-header --format ID 2>/dev/null)
		# "image get" outputs error to stderr.
		if [ -n "$id" ]; then
			echo $id
		fi
		;;
	help|*)
		usage_exit
		;;
esac
