#!/bin/sh
prog=$(basename $0)
bindir=$(dirname $(readlink -f $0))
libdir=$(dirname $bindir)/lib

if [ "$1" = "--list-command" ]; then
	echo "list list-summary summary id help"
	exit 0
fi

. $libdir/common.subr

USAGE="usage:
    $OCEAN_COMMAND $prog list <domain> [args for doctl]
    $OCEAN_COMMAND $prog list-summary <domain>
    $OCEAN_COMMAND $prog summary <FQDN>
    $OCEAN_COMMAND $prog id <FQDN>
    $OCEAN_COMMAND $prog help
" # END-QUOTE

cmd=$1
shift
case "$cmd" in
	list)
		usage_exit_unless "$1"
		domain="$1"
		shift
		doctl compute domain records list $domain "$@"
		;;
	list-summary)
		usage_exit_unless "$1"
		doctl compute domain records list "$1" --format ID,Type,Name,Data,TTL
		;;
	summary)
		usage_exit_unless "$1"
		host=${1%%.*}
		domain=${1#*.}
		doctl compute domain records list $domain --format ID,Type,Name,Data,TTL | awk '$2 == "A" && $3 == "'$host'"{ print }'
		;;
	id)
		usage_exit_unless "$1"
		host=${1%%.*}
		domain=${1#*.}
		doctl compute domain records list $domain --format ID,Type,Name,Data,TTL | awk '$2 == "A" && $3 == "'$host'"{ print $1 }'
		;;
	help|*)
		usage_exit
		;;
esac
